appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: XL4iSlaiLoVLHqrHPDDRl/EERZ9LYCJj/VqB4cTwTLA8CHqWr7v33yeU+1HcNMvAZKnu2HM/tm+rLsOZ9o3I4PpjfRpW3kNRMg7nRJ7SkkayelS4Zph7KzYTP0IJNjSiFAj3wdql5kowTsqMixcT8X53zj8UPqnYrVPeiOj6RV5Lei+dAWtg61toAVn29FI8a9B00TxZRMN/iyFUvalb10pX907pyYm4ovxTTWdQq+fulQXxq48lXLZnqO4YAduiOIXFfz1fjxqJRHNlOm5IgY3Ivit0lOOe0QSn9g/Eqrlu/AC/uidWuZjnaQPgVxF+y/xCPB4u5lLqNnosrlc5QRpR/Rg5xralDnT1OfkmaZ7ZeQbh8vZdBPUVQtnXRwY9wORs76xlCF/uZ8PhU9MxBUBI3UUz6uTbmY9F2NPzNHbmNHttELJhUo6P5mwZIv+7TWlp7Zu/W2s1f0F8T7uRO4jE2QCdpSBynxtStjQeAi6i/7HG1xK5Q0x3WthF8i3Cb05v48/G3XI7A+qjkcwb4LzT2nyf+/dH/gP14+NeqWZJ4fMTfDDwAOrOo+ytcoYeXyaRK5exZmVK2RrffEnmaYybmm3onO9HiARfJX9qnM2byhf/UW9NBEX2rKu8lz+jljFqzREHk9qHOUy4MhY6CvwOTs986K7SIajnupBzxu0=}
